src/Entity/DemandeMission.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use App\Entity\Employe;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use App\Repository\DemandeMissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;

#[ORM\Entity(repositoryClass: DemandeMissionRepository::class)]

class DemandeMission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $numMiss = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateCreation = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Ce champ est obligatoire")]
    private ?string $Sujet = null;
    #[ORM\Column]
    private $supprime = false;
    #[ORM\ManyToOne(inversedBy: 'DemMiss')]
    #[Assert\NotBlank]
    private ?Categorie $categorie = null;
    #[ORM\ManyToOne(inversedBy: 'missions')]
    #[Assert\NotBlank]
    private ?Destination $destination = null;

    #[ORM\ManyToOne(inversedBy: 'affMiss')]
    private ?Voiture $voiture = null;

    #[ORM\ManyToMany(targetEntity: Employe::class, inversedBy: 'demandeMissions')]
    private Collection $Employes;

    #[ORM\ManyToOne(inversedBy: 'missions')]
    private ?Employe $employe = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Ce champ est obligatoire")]
    private ?string $materiel = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: "Ce champ est obligatoire")]
    #[GreaterThanOrEqual(propertyPath: "DateCreation", message: "La date de création doit être supérieure ou égale à la date de début.")]
    private ?\DateTimeInterface $DateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: "Ce champ est obligatoire")]
    #[GreaterThan(propertyPath: "DateDebut", message: "La date de fin doit être supérieure à la date de début.")]
    private ?\DateTimeInterface $DateFin = null;

    #[ORM\ManyToOne(inversedBy: 'Nomdem')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'RapMiss')]
    private ?Rapport $rapport = null;

    #[ORM\Column]
    private ?bool $valider = false;

    #[ORM\Column]
    private ?bool $ordvalid = false;




    #[ORM\Column]
    private ?bool $payer = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $accompext = null;



    public function __construct()
    {
        $this->Employes = new ArrayCollection();
        $this->DateCreation = new \DateTime();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumMiss(): ?string
    {
        return $this->numMiss;
    }

    public function setNumMiss(string $numMiss): self
    {
        $this->numMiss = $numMiss;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(?DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }
    public function getSujet(): ?string
    {
        return $this->Sujet;
    }

    public function setSujet(?string $Sujet): self
    {
        $this->Sujet = $Sujet;

        return $this;
    }
    public function isSuprrimer(): ?bool
    {
        return $this->supprime;
    }
    public function setSuprrimer(bool $supprime): void
    {
        $this->supprime = $supprime;
    }
    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }
    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
    public function getDestination(): ?Destination
    {
        return $this->destination;
    }
    public function setDestination(?Destination $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->Employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->Employes->contains($employe)) {
            $this->Employes->add($employe);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        $this->Employes->removeElement($employe);

        return $this;
    }

    public function getEmploye(): ?Employe
    {
        return $this->employe;
    }

    public function setEmploye(?Employe $employe): self
    {
        $this->employe = $employe;

        return $this;
    }

    public function getMateriel(): ?string
    {
        return $this->materiel;
    }

    public function setMateriel(?string $materiel): self
    {
        $this->materiel = $materiel;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRapport(): ?Rapport
    {
        return $this->rapport;
    }

    public function setRapport(?Rapport $rapport): self
    {
        $this->rapport = $rapport;

        return $this;
    }

    public function isValider(): ?bool
    {
        return $this->valider;
    }

    public function setValider(bool $valider): self
    {
        $this->valider = $valider;

        return $this;
    }

    public function isOrdvalid(): ?bool
    {
        return $this->ordvalid;
    }

    public function setOrdvalid(bool $ordvalid): self
    {
        $this->ordvalid = $ordvalid;

        return $this;
    }

    public function isPayer(): ?bool
    {
        return $this->payer;
    }

    public function setPayer(bool $payer): self
    {
        $this->payer = $payer;

        return $this;
    }

    public function getAccompext(): ?string
    {
        return $this->accompext;
    }

    public function setAccompext(string $accompext): self
    {
        $this->accompext = $accompext;

        return $this;
    }
}

templates/ServiceFinancier/facture.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Liste Des Missions Payer
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css') }}">
{% endblock %}
{% block body %}
	<style>
		h1,
		hr,
		.icon {
			color: #05459D;
		}
		h1 {
			border-bottom: 3px solid #05459D;
			padding-bottom: 10px;
		}
	</style>
	<br><br>
	<h1>
		<span class="icon">
			<i class="bi bi-currency-dollar"></i>
		</span>Liste Des Missions Payer
	</h1>

	<br>
	<div class="card shadow-sm">
		<div class="card-header bg-light">
			<h4 class="card-title mb-0 text-muted">Rechercher</h4>
		</div>
		<div class="card-body">
			<div class="form-row">
				<div class="col">
					<label for="searchInputName" class="form-label">Rechercher par nom:</label>
					<input type="text" class="form-control" id="searchInputName" placeholder="Entrez le nom de l'employé">
				</div>
				<div class="col">
					<label for="searchInputMonth" class="form-label">Rechercher par mois:</label>
					<input type="text" class="form-control" id="searchInputMonth" placeholder="Entrez le mois de la mission">
				</div>

			</div>
		</div>
	</div>

	<br>
	<table class="table table-hover">
		<thead>

			<tr class="table-primary" align="center">
				<th>Destination</th>
				<th>Sujet</th>
				<th>Date Debut</th>
				<th>Date Fin</th>
				<th>Demandeur</th>
				<th>Accompagnant</th>
				<th>Payer</th>
			</tr>
		</thead>
		<tbody class="table-group-divider " align="center">
			{% for mission in Mission %}


				<tr align="center">
					<td class="table-light">
						{{mission.Destination}}
					</td>
					<td>
						{{mission.Sujet}}
					</td>
					<td class="table-light">
						{{mission.DateDebut|date('d-m-Y H:i:s')}}
					</td>

					<td>
						{{mission.DateFin|date('d-m-Y H:i:s')}}
					</td>

					<td class="table-light">
						{% for emp in employe %}
							{% if mission.user is not null and emp.user is not null and mission.user.id == emp.user.id %}
								{{ emp.NomPrenom }}
							{% endif %}
						{% endfor %}


					</td>
					<td>
						{% for e in mission.Employes %}
							{{e}}
							/
						{% endfor %}
					</td>

					<td class="table-light">
						<div class="btn-group gap-2" role="group">
							<a class="btn btn-primary btn-sm" href="{{ path('fact_payer',{id: mission.id})}}">
								<span>
									<i class="bi bi-file-earmark-text"></i>
								</span>
								Note Demandeur</a>
							<a class="btn btn-primary btn-sm" href="{{ path('fact_payeremp',{id: mission.id})}}">
								<span>
									<i class="bi bi-file-earmark-text"></i>
								</span>
								Note Employes</a>
						</div>
					</td>

				</tr>
			{% endfor %}
		</tbody>
	</table>
	<script>
		// Obtenir les éléments des champs de recherche
var searchBoxName = document.getElementById("searchInputName");
var searchBoxMonth = document.getElementById("searchInputMonth");

// Ajouter un event listener aux champs de recherche
searchBoxName.addEventListener("keyup", filterTable);
searchBoxMonth.addEventListener("keyup", filterTable);

function filterTable() {
var searchTermName = searchBoxName.value.toLowerCase().trim();
var searchTermMonth = searchBoxMonth.value.toLowerCase().trim();
var rows = document.querySelectorAll("table tbody tr");

// Boucle sur toutes les lignes du tableau
for (var i = 0; i < rows.length; i++) {
var rowTextName = rows[i].querySelectorAll("td")[4].textContent.toLowerCase().trim();
var rowTextMonth = rows[i].querySelectorAll("td")[2].textContent.toLowerCase().trim();

// Masquer la ligne si le terme de recherche n'est pas trouvé
if (searchTermName !== "" && rowTextName.indexOf(searchTermName) === -1) {
rows[i].style.display = "none";
} else if (searchTermMonth !== "" && rowTextMonth.indexOf(searchTermMonth) === -1) {
rows[i].style.display = "none";
} else {
rows[i].style.display = "";
}
}
}
	</script>

{% endblock %}

templates/ServiceFinancier/fnstats.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Statistique
{% endblock %}

{% block body %}
	<style>
		h1,
		hr,
		.icon {
			color: #05459D;
		}
		h1 {
			border-bottom: 3px solid #05459D;
			padding-bottom: 10px;

		}
	</style>
	<br>
	<h1>
		<span>
			<i class="bi bi-bar-chart-steps"></i>
		</span>Statistique</h1>
	<br>
	<canvas id="graphsg" width="400" height="100"></canvas>

	<script>

		let Missions = document.querySelector("#graphsg")
let Misschart = new Chart(graphsg, {
type: "horizontalBar",
data: {
labels: {{ datesfn|raw }},
datasets: [
{
label: "nombre de mission payeé",
data: {{ misscountfn|raw }},
backgroundColor: [
"rgba(255, 99, 132, 0.2)",
"rgba(255, 159, 64, 0.2)",
"rgba(255, 205, 86, 0.2)",
"rgba(75, 192, 192, 0.2)",
"rgba(54, 162, 235, 0.2)",
"rgba(153, 102, 255, 0.2)",
"rgba(201, 203, 207, 0.2)"
],
borderColor: [
"rgb(255, 99, 132)",
"rgb(255, 159, 64)",
"rgb(255, 205, 86)",
"rgb(75, 192, 192)",
"rgb(54, 162, 235)",
"rgb(153, 102, 255)",
"rgb(201, 203, 207)"
],
borderWidth: 1

}
]

},
options: {
scales: {
xAxes: [
{
ticks: {
beginAtZero: true,
stepSize: 1
}
}
]
}
}
})
	</script>
	<div class="alert alert-info mt-3" role="alert">
		<h4 class="alert-heading">
			<span>
				<i class="bi bi-lightbulb"></i>
			</span>Remarque</h4>
		<p class="mb-0">
			Ce graphique représente le nombre de missions payées chaque mois de l'année. Comme vous pouvez le voir, l'axe des X indique les mois de l'année, tandis que l'axe des Y affiche le nombre de missions payées.
																											
																											Chaque barre sur le graphique représente le nombre de missions payées au cours d'un mois particulier. La hauteur de chaque barre indique le nombre de missions payées pour ce mois spécifique.</p>
	</div>

{% endblock %}

templates/ServiceFinancier/impfac.html.twig
{% block body %}
	{% block stylesheets %}

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
	{% endblock %}
	<style>
		body {
			font-family: Arial, sans-serif;
			margin: 0;
			padding: 0;
		}

		header {
			background-color: #fff;
			padding: 10px;
			display: flex;
			align-items: center;
			justify-content: space-between;
			position: flex;
			top: 0;
			left: 0;
			right: 0;
			z-index: 1;
		}

		.header-left {
			display: flex;
			align-items: center;
		}

		.header-left img {
			height: 45px;
			margin-right: 0;
		}
		.header-right img {
			height: 90px;
		}
		@media print {
			.header-right img {
				display: block;
			}
		}

		@media print {
			#print-button {
				display: none;
			}
		}
		@media print {
			#print {
				display: none;
			}
		}
		footer {
			background-color: #ffffff;
			padding: 40px 0;
		}

		.footer-container {
			display: flex;
			flex-wrap: wrap;
			justify-content: space-between;
			max-width: 1200px;
			margin: 0 auto;
		}

		.footer-logo img {
			max-width: 200px;
		}


		.separator {
			height: 5px;
			background-color: #0e0e0e;
			border: none;
			border-top: 1px solid #0c0c0c;
			border-bottom: 1px solid #090909;
		}
	</style>
	<header>
		<div class="header-left">
			<img src="{{ asset('logo/logo-site-1.png', null) }}" alt="Image de left">
		</div>
		<div class="header-right">
			<img src="{{ asset('logo/ministere.png', null) }}" alt="Image de right">
		</div>
	</header>
	<div style=" padding: 20px; text-align: center;">
		<h1 style="color: #333;">Note de calcul de l'allocation quotidienne de déplacement</h1>
		<hr style="border: 1px solid #333; margin: 20px auto;">
		<p style="font-size: 18px; line-height: 1.5; margin-bottom: 10px; text-align: left; text-justify: inter-word;">


			Estimation des honoraires de M
			<strong>
				{% for emp in employeUser %}
					{% if Mission.user is not null and emp.user is not null and Mission.user.id == emp.user.id %}
						{{ emp.NomPrenom }}
					{% endif %}
				{% endfor %}
			</strong>
			titulaire de la carte d'identité nationale  N° :
			<strong>
				{% for emp in employeUser %}
					{% if Mission.user is not null and emp.user is not null and Mission.user.id == emp.user.id %}
						{{ emp.numcarte }}
					{% endif %}
				{% endfor %}
			</strong>

			, et titulaire du compte courant numéro :
			<strong>
				{% for emp in employeUser %}
					{% if Mission.user is not null and emp.user is not null and Mission.user.id == emp.user.id %}
						{{ emp.numcarte }}
					{% endif %}
				{% endfor %}
			</strong>
			, pour les missions qu'il a effectuées au cours de la période s'étendant de:
			<strong>{{ Mission.DateDebut|date('d-m-Y') }}</strong>
			<br>
			à :
			<strong>{{ Mission.DateFin|date('d-m-Y') }}</strong>

			, conformément aux informations figurant dans le tableau suivant :


		</p>
	</div>


	<table class="table table-hover">
		<thead>
			<tr class="table-primary" align="center">
				<th>Destination</th>
				<th>Date Aller-Retour</th>
				<th>Horaire Aller-Retour</th>
				<th>Allocation journalière</th>
				<th>Nombre de jours</th>
				<th>Total</th>
				<th>Observation</th>


			</tr>
		</thead>
		<tbody class="table-group-divider" align="center">

			<tr align="center">
				<td>
					{{Mission.Destination}}
				</td>
				<td class="table-light">
					de
					{{Mission.DateDebut|date('d-m-Y')}}
					<br>
					à
					{{Mission.DateFin|date('d-m-Y')}}
				</td>
				<td class="table-light">
					de
					{{Mission.DateDebut|date('H:i:s')}}
					à
					{{Mission.DateFin|date('H:i:s')}}
				</td>
				<td>
					{% for emp in employeUser %}
						{% if Mission.user is not null and emp.user is not null and Mission.user.id == emp.user.id %}
							{% if emp.profession == 'Administrateur en chef' or emp.profession == 'ingénieur en chef' or emp.profession == 'ingénieur principale' %}
								{% set salaire = emp.profession.montant %}
								{% set userSalaire = salaire * periode %}
								{{ salaire }}
							{% endif %}
						{% endif %}
					{% endfor %}
				</td>
				<td>{{periode}}</td>
				<td>
					{% for emp in employeUser %}
						{% if Mission.user is not null and emp.user is not null and Mission.user.id == emp.user.id %}
							{% if emp.profession == 'Administrateur en chef' or emp.profession == 'ingénieur en chef' or emp.profession == 'ingénieur principale' %}
								{% set salaire = emp.profession.montant %}
								{% set userSalaire = salaire * periode %}
								{{ userSalaire }}
							{% endif %}
						{% endif %}
					{% endfor %}
				</td>

				<td>{{Mission.Sujet}}</td>
			</tr>
		</tbody>
	</td>
</tr></tbody></table><div style="display: flex; justify-content: space-between; margin-top: 20px;"><div>
<p style="margin-bottom: 5px;">Signature du Président :</p></div><div>
<p style="margin-bottom: 5px;">Signature de Bénéficiaire :</p></div></div>{% if is_granted('ROLE_FINANCIER') %}<button id="print-button" class="btn btn-success">
<span>
	<i class="bi bi-printer"></i>
</span>Imprimer</button><a id="print" class="btn btn-primary" href="{{ path('misspayer-miss')}}">Retour</a>{% endif %}<br><br><br><br><br><br><br><br><br><div class="separator"></div><footer><div class="footer-container">
<div class="footer-logo"><img src="{{ asset('logo/logo-site-1.png', null) }}" alt="Your Logo"></div><br><br><div>
	<p>
		<i class="bi bi-geo-alt"></i>Université de Sfax. Route de l'Aéroport Km 0.5 BP 1169 .3029 Sfax</p>
	<p>
		<i class="bi bi-telephone"></i>+216 74 244 423 - +216 74 248 233 - +216 74 242 951 - +216
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												                    74 247 954</p>
	<p>
		<i class="bi bi-globe"></i>universite.sfax@usf.tn</p>
</div></div></footer><script>var printButtons = document.querySelectorAll('#print-button');

for (var i = 0; i < printButtons.length; i++) {
printButtons[i].addEventListener('click', function () {
var row = this.parentNode.parentNode;
var printContents = row.innerHTML;
var originalContents = document.body.innerHTML;
document.body.innerHTML = printContents;
window.print();
document.body.innerHTML = originalContents;

});
}</script>{% endblock %}

templates/ServiceFinancier/impfacemp.html.twig
{% block body %}
{% block stylesheets %}

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
{% endblock %}
<style>
	body {
		font-family: Arial, sans-serif;
		margin: 0;
		padding: 0;
	}

	header {
		background-color: #fff;
		padding: 10px;
		display: flex;
		align-items: center;
		justify-content: space-between;
		position: flex;
		top: 0;
		left: 0;
		right: 0;
		z-index: 1;
	}

	.header-left {
		display: flex;
		align-items: center;
	}

	.header-left img {
		height: 45px;
		margin-right: 0;
	}
	.header-right img {
		height: 90px;
	}
	@media print {
		.header-right img {
			display: block;
		}
	}

	@media print {
		#print-button {
			display: none;
		}
	}
	@media print {
		#print {
			display: none;
		}
	}
	footer {
		background-color: #ffffff;
		padding: 40px 0;
	}

	.footer-container {
		display: flex;
		flex-wrap: wrap;
		justify-content: space-between;
		max-width: 1200px;
		margin: 0 auto;
	}

	.footer-logo img {
		max-width: 200px;
	}


	.separator {
		height: 5px;
		background-color: #0e0e0e;
		border: none;
		border-top: 1px solid #0c0c0c;
		border-bottom: 1px solid #090909;
	}
</style>
{% for emp in Mission.employes  %}
	<header>
		<div class="header-left">
			<img src="{{ asset('logo/logo-site-1.png', null) }}" alt="Image de left">
		</div>
		<div class="header-right">
			<img src="{{ asset('logo/ministere.png', null) }}" alt="Image de right">
		</div>
	</header>
	<div style=" padding: 20px; text-align: center;">
		<h1 style="color: #333;">Note de calcul de l'allocation quotidienne de déplacement</h1>
		<hr style="border: 1px solid #333; margin: 20px auto;">

	</div>


	<p style="font-size: 18px; line-height: 1.5; margin-bottom: 10px; text-align: left; text-justify: inter-word;">


		Estimation des honoraires de M
		<strong>{{ emp.NomPrenom }}
		</strong>
		titulaire de la carte d'identité nationale  N° :
		<strong>{{emp.numcarte}}</strong>
		, et titulaire du compte courant numéro :
		<strong>{{emp.numcompte}}</strong>
		, pour les missions qu'il a effectuées au cours de la période s'étendant de:
		<strong>{{ Mission.DateDebut|date('d-m-Y') }}</strong>
		<br>
		à :
		<strong>{{ Mission.DateFin|date('d-m-Y') }}</strong>

		, conformément aux informations figurant dans le tableau suivant :


	</p>
	<table class="table table-hover">
		<thead>
			<tr class="table-primary" align="center"></tr>
			<tr class="table-primary" align="center">
				<th>Destination</th>
				<th>Date Aller-Retour</th>
				<th>Horaire Aller-Retour</th>
				<th>Allocation journalière</th>
				<th>Nombre de jours</th>
				<th>Total</th>
				<th>Observation</th>
			</tr>
		</thead>
	</tr>
</thead>
<tbody class="table-group-divider" align="center">

	<tr align="center">
		<td>
			{{Mission.Destination}}
		</td>
		<td class="table-light">
			de
			{{Mission.DateDebut|date('d-m-Y')}}
			<br>
			à
			{{Mission.DateFin|date('d-m-Y')}}
		</td>
		<td class="table-light">
			de
			{{Mission.DateDebut|date('H:i:s')}}
			à
			{{Mission.DateFin|date('H:i:s')}}
		</td>
		<td>{{emp.profession.montant}}</td>
		<td>{{periode}}</td>
		<td>
			{{salaries[emp.id] }}</td>
		<td>{{Mission.Sujet}}</td>

	</tr>
</tbody></table><div style="display: flex; justify-content: space-between; margin-top: 20px;">
<div>
	<p style="margin-bottom: 5px;">Signature du Président :</p>
</div>
<div>
	<p style="margin-bottom: 5px;">Signature du Bénéficiaire :</p>
</div></div>{% if is_granted('ROLE_FINANCIER') %}
<button id="print-button" class="btn btn-success">
	<span>
		<i class="bi bi-printer"></i>
	</span>Imprimer</button>
<a id="print" class="btn btn-primary" href="{{ path('misspayer-miss')}}">Retour</a>{% endif %}<br><br><br><br><br><br><br><br><br><div class="separator"></div><footer>
<div class="footer-container">
	<div class="footer-logo">
		<img src="{{ asset('logo/logo-site-1.png', null) }}" alt="Your Logo"></div><br><br><div>

		<p>
			<i class="bi bi-geo-alt"></i>
			Université de Sfax. Route de l'Aéroport Km 0.5 BP 1169 .3029 Sfax</p>

		<p>
			<i class="bi bi-telephone"></i>
			+216 74 244 423 - +216 74 248 233 - +216 74 242 951 - +216
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										                    74 247 954</p>
		<p>
			<i class="bi bi-globe"></i>
			universite.sfax@usf.tn</p>
	</div>
</div></footer>{% endfor %}<script>var printButtons = document.querySelectorAll('#print-button');

for (var i = 0; i < printButtons.length; i++) {
printButtons[i].addEventListener('click', function () {
var row = this.parentNode.parentNode;
var printContents = row.innerHTML;
var originalContents = document.body.innerHTML;
document.body.innerHTML = printContents;
window.print();
document.body.innerHTML = originalContents;

});
}</script>{% endblock %}